name: S&P500 技术指标监控系统

on:
  schedule:
    - cron: '0 2 * * *'  # 每天 UTC 2:00 (北京时间 10:00) 运行
  workflow_dispatch:  # 允许手动触发

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v4
        
      - name: 设置 Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          
      - name: 安装依赖
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: 运行监控脚本
        env:
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
        run: python main.py
        
      - name: 提交生成的图表
        if: success()
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add sp500_45wma_chart.png || true
          git commit -m "更新 S&P500 图表 [自动]" || true
          git push || true