name: SP500 Technical Monitor

# 设置运行时间，默认每天UTC 0:00运行一次（相当于北京时间早上8:00）
on:
  schedule:
    - cron: '0 0 * * *'  # 每天运行一次
  workflow_dispatch:  # 允许手动触发

jobs:
  run-monitor:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
        
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        
    - name: Run monitoring system
      env:
        EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
      run: |
        python main.py --mode auto --notify --plot --save-data
        
    - name: Upload reports and charts
      uses: actions/upload-artifact@v4
      with:
        name: reports-charts
        path: |
          reports/
          logs/latest.log
          
    - name: Commit and push latest data
      run: |
        git config --global user.name "GitHub Actions Bot"
        git config --global user.email "actions@github.com"
        
        # Add any new data files
        git add data/latest_data.csv
        git add reports/
        
        # Get current date for commit message
        DATE=$(date '+%Y-%m-%d')
        
        # Try to commit and push, but don't fail if there's nothing to commit
        git commit -m "Update data and reports - $DATE" || echo "No changes to commit"
        git push || echo "No changes to push"